# Generated by Django 5.1 on 2024-11-21 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=10)),
                ('prenume', models.CharField(blank=True, max_length=50)),
                ('varsta', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('tip_mesaj', models.CharField(choices=[('reclamatie', 'Reclamatie'), ('intrebare', 'Intrebare'), ('review', 'Review'), ('cerere', 'Cerere'), ('programare', 'Programare')], max_length=20)),
                ('subiect', models.CharField(max_length=100)),
                ('zile_asteptare', models.PositiveIntegerField()),
                ('mesaj', models.TextField()),
                ('data_trimitere', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('loyalty', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
