# Generated by Django 5.1 on 2024-12-28 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_promotie_vizualizare'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('vizualizare_oferta', 'Poate vizualiza oferta'),)},
        ),
    ]
