# Generated by Django 5.1 on 2025-01-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_book_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='restock_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
