# Generated by Django 5.1 on 2024-10-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prajitura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=50, unique=True)),
                ('descriere', models.TextField(blank=True, null=True)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=8)),
                ('gramaj', models.PositiveIntegerField()),
                ('tip_produs', models.CharField(choices=[('cofetarie', 'Cofetarie'), ('patiserie', 'Patiserie'), ('gelaterie', 'Gelaterie')], default='cofetarie', max_length=20)),
                ('calorii', models.PositiveIntegerField()),
                ('categorie', models.CharField(choices=[('comanda speciala', 'Comanda Speciala'), ('aniversara', 'Aniversara'), ('editie limitata', 'Editie Limitata'), ('pentru copii', 'Pentru Copii'), ('dietetica', 'Dietetica'), ('comuna', 'Comuna')], default='comuna', max_length=20)),
                ('pt_diabetici', models.BooleanField(default=False)),
                ('imagine', models.URLField(blank=True, max_length=300, null=True)),
                ('data_adaugare', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
